# Generated by Django 5.2.6 on 2025-11-12 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/'),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
