# Generated by Django 5.2.6 on 2025-11-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_evento_foto_delete_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
    ]
