# Generated by Django 5.2.6 on 2025-09-30 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('tenant_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=255)),
                ('dominio', models.CharField(max_length=255)),
                ('logo_url', models.CharField(max_length=500)),
                ('paleta_de_cores', models.CharField(max_length=255)),
                ('criado_em', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
