# Generated by Django 5.2.6 on 2025-11-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='logo_url',
            field=models.ImageField(blank=True, null=True, upload_to='tenants/'),
        ),
    ]
