# Generated by Django 5.2.6 on 2025-11-13 19:43

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='paleta_de_cores',
            field=colorfield.fields.ColorField(default='#FF0000', image_field=None, max_length=25, samples=None),
        ),
    ]
