# Generated by Django 5.2.6 on 2025-10-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sobre_mim',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
