# Generated by Django 5.2.6 on 2025-11-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_sobre_mim'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sobre_mim', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
