# Generated by Django 5.2.6 on 2025-11-14 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_sobre_mim'),
        ('tenants', '0003_alter_tenant_paleta_de_cores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='tenants.tenant'),
        ),
    ]
