# Generated by Django 5.2.6 on 2025-11-21 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_tenant'),
        ('accounts', '0003_profile'),
    ]

    operations = [
    ]
