# Generated by Django 5.2.6 on 2025-10-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points',
            name='pontos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
