# Generated by Django 5.2.6 on 2025-10-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_alter_points_pontos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_task',
            name='tenant',
        ),
    ]
