# Generated by Django 5.2.6 on 2025-10-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_remove_user_task_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_task',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
