# Generated by Django 5.2.6 on 2025-10-09 23:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_alter_user_task_concluido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_task',
            unique_together={('user', 'task')},
        ),
    ]
