# Generated by Django 5.2.6 on 2025-11-21 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_alter_user_task_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='pontos',
            new_name='pontos_total',
        ),
        migrations.AddField(
            model_name='points',
            name='pontos_atual',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='points',
            name='nivel',
            field=models.CharField(default='Iniciante', max_length=50),
        ),
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('conquista_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='conquistas/')),
                ('ranking_mensal', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('task_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conquista_associada', to='gamification.task')),
            ],
        ),
        migrations.CreateModel(
            name='UserConquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebida', models.DateTimeField(auto_now_add=True)),
                ('mes', models.PositiveIntegerField(blank=True, null=True)),
                ('ano', models.PositiveIntegerField(blank=True, null=True)),
                ('conquista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.conquista')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'conquista', 'mes', 'ano')},
            },
        ),
    ]
