# Generated by Django 5.2.6 on 2025-11-21 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_rename_pontos_points_pontos_total_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='points',
            old_name='pontos_atual',
            new_name='points_atual',
        ),
        migrations.RenameField(
            model_name='points',
            old_name='pontos_total',
            new_name='points_total',
        ),
        migrations.RenameField(
            model_name='userconquista',
            old_name='data_recebida',
            new_name='recebido_em',
        ),
        migrations.RemoveField(
            model_name='conquista',
            name='task_relacionada',
        ),
        migrations.AlterUniqueTogether(
            name='userconquista',
            unique_together={('user', 'conquista')},
        ),
        migrations.AddField(
            model_name='task',
            name='conquista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_with_badge', to='gamification.conquista'),
        ),
        migrations.AlterField(
            model_name='userconquista',
            name='conquista',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_received', to='gamification.conquista'),
        ),
        migrations.AlterField(
            model_name='userconquista',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquists_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='userconquista',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='userconquista',
            name='mes',
        ),
    ]
