# Generated by Django 5.2.6 on 2025-11-22 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_rename_pontos_atual_points_points_atual_and_more'),
        ('tenants', '0003_alter_tenant_paleta_de_cores'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserConquista',
            new_name='User_Conquista',
        ),
        migrations.AddField(
            model_name='conquista',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='tenants.tenant'),
        ),
    ]
